### PR TITLE
Allow static linking of go-clang using the "static" build tag

### PR DESCRIPTION
**Pull request by zimmski**
The dynamic build is the default and still requires a libclang in a library directory.

Fixes go-clang/gen#116

### CODE REVIEW

**Comment by marxriedl** [comment]
LGTM

**Comment by zimmski** [comment]
@go-clang/dev  I pressed the "update branch" button for this PR and merged it. The result can be seen here https://github.com/go-clang/bootstrap/commits/master which shows that the repository history could be flooded with unneeded merge commits such as https://github.com/go-clang/bootstrap/commit/3dae86ad0e566e645c870f530893928578ef7af6 I am proposing that we always rebase locally (and tell contributors to do that too) until GitHub introduces a better way.

**Comment by zchee** [comment]
@zimmski Hi, thanks for support static build.

BTW, I finally started working on a project that uses go-clang.
I want to use the v3.9, but it seems not bumped this change to each versions repository. Is there a problem to backport it?

**Comment by zimmski** [comment]
I will update the version repositories.

**Comment by zchee** [comment]
@zimmski Thanks :)

BTW, this is other topic. and sorry if you already know.
I found references that can `v3.9` testing in travis ci. but needs `sudo`
https://github.com/zchee/go-clang-v3.9/blob/ci-llvm-3.9/.travis.yml
travis still does not run the job on my repository, so doesn't know test result. But it might be worth a try if use `sudo: required` is no problem.

**Comment by zimmski** [comment]
I found a problem, need to fix it first. This might take a while. 

Concerning the 3.9 packages: I saw that, but I find it better when there is official TravisCI support for these packages. Because if we add an exception to the 3.9 repository we need to maintain that too.

**Comment by zchee** [comment]
@zimmski 
> I found a problem, need to fix it first. This might take a while.

I see. I'm interesting that's problem, but I can wait. thanks works.

> Concerning the 3.9 packages: I saw that, but I find it better when there is official TravisCI support for these packages. Because if we add an exception to the 3.9 repository we need to maintain that too.

I understand. Yes, best way is support officially. I'm not sure why travis still doesn't support it...
Well, thanks again polite reply.

**Comment by zimmski** [comment]
@zchee: Version repositories are up to date, please give it a whirl and if you find a problem please open an issue in golang/gen. Looking forward to seeing your new project!

**Comment by zchee** [comment]
@zimmski Wow!! Thanks quickly :D Got it, will report if have any problem.

I planned to develop the alternative [rtags](https://github.com/Andersbakken/rtags) and google/navc, which is C/C++ AST index rpc server.
https://github.com/zchee/clang-server
I'm still Go and C newbie, but do my best :)
And, I want to some clang-extra-tools bindings for Go. I'll write it with reference to go-clang/gen.

Thanks again polite support.
I'm also interested in the future of sergi/go-diff ;)

**Comment by zimmski** [comment]
Alright, sound interesting. Let me know how it is going :-)

I will hopefully finish things with go-diff this week. If you want to help with that project too, I would be happy to fill you in.

**Pull request merged**
